# Generated by Django 5.0.3 on 2025-08-05 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
