# Generated by Django 5.0.3 on 2025-08-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_slot_slot_time_slot_date_slot_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='available_slots',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.slot'),
        ),
    ]
